### ISSUE TITLE
StickTo error

### ISSUE THREAD

**Issue by CHEWX** [somewebmedia/hc-sticky#41] opened 2018-01-23 22:44 UTC
Hi, 

Nice job on version 2!

It mentions in brackets for `stickTo`, `(parent element)`, however is errors, if nothing is set. 

`Cannot read property 'indexOf' of undefined`

It works ok, if `stickTo` is not set and `top` is explicily set to `0`, even though it is in the defaults.

Thanks,
Tom

**Comment by somewebmedia** [comment] 2018-01-24 12:09
Hi @CHEWX, could you please provide me with some demo page where I could take a look at what is happening, because I can't re-create the problem you are experiencing.

Thanks.

**Comment by CHEWX** [comment] 2018-01-24 12:31
Hi @somewebmedia ,

You can see the replication here — https://codepen.io/anon/pen/KZLvOJ

Thanks

**Comment by carasmo** [comment] 2018-01-28 19:58
@CHEWX 

You have tell it what to stickTo and the class sticky is reserved for the plugin, so make the element you want to stick another class. Here's a modified pen:

https://codepen.io/anon/pen/VQZVjW

**Comment by CHEWX** [comment] 2018-01-28 22:09
@carasmo It's an error with the plugin.

The plugin should default to the `parent element`, this shouldn't be explicit. 

It defaults correctly when parsing `{ top: 0 }`, however, this shouldn't be needed.

When initialising the plugin, in most cases, there shouldn't be a need to add any options. They are options, to modify the default behaviour.

As such, the default behaviour is problematic, hence the issue.

Thanks for your pen, however, it doesn't address the issue.

**Comment by carasmo** [comment] 2018-01-29 00:10
I see. I assumed that null meant that it must be filled in and parent element in parenthesis meant I had to stick in the class or id. 
<img width="950" alt="screen shot 2018-01-28 at 7 08 52 pm" src="https://user-images.githubusercontent.com/1124594/35488983-bdf1103a-045e-11e8-952f-e9076047f12d.png">

**Comment by somewebmedia** [comment] 2018-01-31 21:01
@CHEWX I can confirm it's the bug in the plugin. I'm currently on vacation, will fix it as soon as I get back.

**Comment by somewebmedia** [comment] 2018-02-24 14:28
@CHEWX Should be fixed with the latest (`2.1.2`) version.

**Closed by somewebmedia** 2018-02-24 14:28 UTC
